# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
# Import API key
from config import g_key


%matplotlib inline

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
csv_path='../output_data/cities_df.csv'
cities_df=pd.read_csv(csv_path)
cities_df.head()

,Unnamed: 0,Cities,Lat,Lng,Max Temp,Humidity,Cloudiness,Windspeed,Country,Date
0,0,port alfred,-33.59,26.89,61.772,82.0,59.0,3.40,ZA,1.603053e+09
1,1,kruisfontein,-34.00,24.73,55.004,85.0,17.0,1.44,ZA,1.603054e+09
2,2,new norfolk,-42.78,147.06,51.008,73.0,89.0,0.89,AU,1.603054e+09
3,3,rikitea,-23.12,-134.97,74.858,81.0,100.0,8.27,PF,1.603054e+09
4,4,waipawa,-41.41,175.52,57.200,76.0,100.0,10.30,NZ,1.603053e+09

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
humidity=[]
for x in np.arange(0,len(cities_df['Humidity']),1):
    humidity.append((cities_df['Humidity'][x]))
locations=[]
for x in np.arange(0,len(cities_df['Lat']),1):
    locations.append((cities_df['Lat'][x],cities_df['Lng'][x]))

In [12]:
gmaps.configure(api_key=g_key)

figure_layout = { 'width': '1000px', 
                 'height': '400px', 
                 'border': '1px solid black', 
                 'padding': '1px', 'margin': 
                 '0 auto 0 auto' }

In [13]:
fig = gmaps.figure(layout=figure_layout)
fig.add_layer(gmaps.heatmap_layer(locations, weights=humidity))
markers = gmaps.marker_layer(locations)
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(border='1px solid black', height='400px', margin='0 auto 0 auto', padding='1px', wiâ€¦

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [19]:
vac_df=cities_df.loc[cities_df['Max Temp']>70]
vac_df=vac_df.loc[vac_df['Max Temp']<80]
vac_df

,Unnamed: 0,Cities,Lat,Lng,Max Temp,Humidity,Cloudiness,Windspeed,Country,Date
3,3,rikitea,-23.12,-134.97,74.858,81.0,100.0,8.27,PF,1.603054e+09
9,9,vaini,-21.20,-175.20,71.600,83.0,75.0,6.91,TO,1.603053e+09
11,12,padang,-0.95,100.35,77.846,77.0,83.0,1.67,ID,1.603054e+09
13,14,hirara,24.80,125.28,77.792,80.0,58.0,9.50,JP,1.603054e+09
14,15,bengkulu,-3.80,102.27,74.858,93.0,100.0,2.67,ID,1.603054e+09
...,...,...,...,...,...,...,...,...,...,...
530,586,monrovia,6.30,-10.80,78.800,88.0,75.0,3.35,LR,1.603054e+09
535,591,lalmatie,-20.19,57.66,73.400,78.0,40.0,5.10,MU,1.603054e+09
541,597,tahta,26.77,31.50,75.200,41.0,0.0,4.10,EG,1.603053e+09
548,604,ambunti,-4.24,142.84,74.408,97.0,100.0,0.03,PG,1.603054e+09
553,609,sao joao da barra,-21.64,-41.05,75.200,69.0,75.0,7.20,BR,1.603054e+09

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [5]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

NameError: name 'hotel_df' is not defined

In [ ]:
# Add marker layer ontop of heat map


# Display figure