# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
# Import API key
from config import g_key
from pprint import pprint

%matplotlib inline

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
csv_path='../output_data/cities_df.csv'
cities_df=pd.read_csv(csv_path)
cities_df.head()

,Unnamed: 0,Cities,Lat,Lng,Max Temp,Humidity,Cloudiness,Windspeed,Country,Date
0,0,trelew,-43.25,-65.31,57.020,34.0,48.0,6.51,AR,1.603856e+09
1,1,talnakh,69.49,88.40,-3.208,80.0,0.0,2.44,RU,1.603856e+09
2,3,grindavik,63.84,-22.43,41.000,52.0,0.0,12.30,IS,1.603856e+09
3,4,port elizabeth,-33.92,25.57,60.800,87.0,0.0,2.60,ZA,1.603856e+09
4,5,vila franca do campo,37.72,-25.43,62.600,63.0,75.0,2.60,PT,1.603856e+09

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
humidity=[]
for x in np.arange(0,len(cities_df['Humidity']),1):
    humidity.append((cities_df['Humidity'][x]))
locations=[]
for x in np.arange(0,len(cities_df['Lat']),1):
    locations.append((cities_df['Lat'][x],cities_df['Lng'][x]))

In [4]:
gmaps.configure(api_key=g_key)

figure_layout = { 'width': '700px', 
                 'height': '500px', 
                 'border': '1px solid black', 
                 'padding': '1px', 'margin': 
                 '0 auto 0 auto' }

In [6]:
fig = gmaps.figure(layout=figure_layout)
fig.add_layer(gmaps.heatmap_layer(locations, weights=humidity))
fig

Figure(layout=FigureLayout(border='1px solid black', height='500px', margin='0 auto 0 auto', padding='1px', wiâ€¦

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [7]:
vac_df=cities_df.loc[cities_df['Max Temp']>70]
vac_df=vac_df.loc[vac_df['Max Temp']<80]
vac_df=vac_df.loc[vac_df['Windspeed']<10]
vac_df=vac_df.loc[vac_df['Cloudiness']==0]
vac_df

,Unnamed: 0,Cities,Lat,Lng,Max Temp,Humidity,Cloudiness,Windspeed,Country,Date
83,94,senador guiomard,-10.15,-67.74,71.600,100.0,0.0,2.10,BR,1.603856e+09
94,108,aswan,24.09,32.91,74.300,46.0,0.0,3.68,EG,1.603856e+09
117,132,ndele,8.41,20.65,70.286,79.0,0.0,1.16,CF,1.603856e+09
120,135,taoudenni,22.68,-3.98,74.462,21.0,0.0,0.88,ML,1.603856e+09
130,147,suleja,9.18,7.18,75.200,88.0,0.0,1.50,NG,1.603856e+09
148,167,adrar,20.50,-10.07,78.530,21.0,0.0,4.40,MR,1.603856e+09
149,168,werda,-25.27,23.28,75.902,29.0,0.0,6.22,BW,1.603856e+09
155,176,saint-philippe,-21.36,55.77,77.000,53.0,0.0,1.50,RE,1.603856e+09
274,307,nouadhibou,20.93,-17.03,73.400,64.0,0.0,8.20,MR,1.603856e+09
311,347,mayor pablo lagerenza,-19.93,-60.77,74.858,72.0,0.0,2.80,PY,1.603856e+09
326,364,aron,24.38,77.42,79.664,28.0,0.0,2.17,IN,1.603856e+09
338,376,saint-pierre,-21.34,55.48,77.000,53.0,0.0,1.50,RE,1.603856e+09
343,381,karauli,26.50,77.02,79.790,20.0,0.0,2.22,IN,1.603856e+09
375,414,tessalit,20.20,1.01,74.210,20.0,0.0,2.97,ML,1.603856e+09
385,426,nainpur,22.43,80.12,78.800,51.0,0.0,1.15,IN,1.603856e+09
388,429,sarh,9.14,18.39,75.200,88.0,0.0,0.96,TD,1.603856e+09
452,500,santiago del estero,-27.80,-64.26,71.726,47.0,0.0,3.69,AR,1.603856e+09
453,501,sur,22.57,59.53,77.720,53.0,0.0,1.27,OM,1.603856e+09
457,505,safaga,26.73,33.94,73.400,53.0,0.0,4.10,EG,1.603856e+09
482,533,abu dhabi,24.47,54.37,73.400,73.0,0.0,0.50,AE,1.603856e+09
499,550,moissala,8.34,17.77,71.762,86.0,0.0,1.22,TD,1.603856e+09
503,554,illela,13.73,5.30,77.342,18.0,0.0,3.96,NG,1.603856e+09
507,558,geraldton,-28.77,114.60,75.200,47.0,0.0,8.70,AU,1.603856e+09
518,569,morondava,-20.28,44.28,76.640,53.0,0.0,1.16,MG,1.603856e+09

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [8]:
hotel_df=vac_df
print(len(hotel_df))

24

In [9]:
ticker=0
hotel=[]
locations=[]
for x in np.arange(0,len(hotel_df),1):   
    print(f"Proccessing record {ticker+1}")
    url=f"https://maps.googleapis.com/maps/api/place/nearbysearch/json?parameters"
    params={"location":(f"{hotel_df.iloc[ticker][2]},{hotel_df.iloc[ticker][3]}"),
    "radius":"5000","type": "lodging","key": f"{g_key}"}
    response=requests.get(url,params=params).json()
    
    try:
        print(f"Hotel {response['results'][0]['name']} found!")
        hotel.append(response['results'][0]['name'])
       # locations.append((response['results'][0]['geometry']['location']['lat']),(response['results'][0]['geometry']['location']['lng']))
        ticker+=1
    except:
        print("No hotel found within range!")
        hotel.append(None)
        ticker+=1
        pass
hotel_df['Hotel Name']=hotel

Proccessing record 1
Hotel Hotel Rondon found!
Proccessing record 2
Hotel Nuba Nile found!
Proccessing record 3
No hotel found within range!
Proccessing record 4
No hotel found within range!
Proccessing record 5
Hotel Capy Motel found!
Proccessing record 6
No hotel found within range!
Proccessing record 7
No hotel found within range!
Proccessing record 8
Hotel Chambres d'hÃ´te "La TrinitÃ©" found!
Proccessing record 9
Hotel El Medina found!
Proccessing record 10
No hotel found within range!
Proccessing record 11
Hotel Kishan Fruit Company found!
Proccessing record 12
Hotel Lindsey HÃ´tel found!
Proccessing record 13
Hotel Bhanwar Vilas Palace found!
Proccessing record 14
No hotel found within range!
Proccessing record 15
Hotel Railway Rest House found!
Proccessing record 16
Hotel HÃ´tel des Chasses found!
Proccessing record 17
Hotel Hotel Urbano found!
Proccessing record 18
Hotel Sur Plaza Hotel found!
Proccessing record 19
Hotel Lamar Resort Abu Soma found!
Proccessing record 20
Hotel Beach Rotana found!
Proccessing record 21
No hotel found within range!
Proccessing record 22
No hotel found within range!
Proccessing record 23
Hotel Broadwater Mariner Resort found!
Proccessing record 24
Hotel La Case Bambou found!

In [10]:
hotel_df=hotel_df.dropna()
locations=[]
names=[]
cities=[]
countries=[]
params=[]
locations=hotel_df.iloc[:,2:4]
names=hotel_df['Hotel Name'].tolist()
cities=hotel_df['Cities'].tolist()
countries=hotel_df['Country'].tolist()
for x in np.arange(0,len(names),1):
    params.append(f"Name: {names[x]}, City: {cities[x]}, Country: {countries[x]}")

# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{Cities}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [11]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations,info_box_content=params)
fig.add_layer(markers)

# Display figure
plt.savefig('../output_data/hotel_map.png')
fig

Figure(layout=FigureLayout(border='1px solid black', height='500px', margin='0 auto 0 auto', padding='1px', wiâ€¦