# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [33]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
# Import API key
from config import g_key
from pprint import pprint

%matplotlib inline

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [34]:
csv_path='../output_data/cities_df.csv'
cities_df=pd.read_csv(csv_path)
cities_df.head()

,Unnamed: 0,Cities,Lat,Lng,Max Temp,Humidity,Cloudiness,Windspeed,Country,Date
0,0,port alfred,-33.59,26.89,61.772,82.0,59.0,3.40,ZA,1.603053e+09
1,1,kruisfontein,-34.00,24.73,55.004,85.0,17.0,1.44,ZA,1.603054e+09
2,2,new norfolk,-42.78,147.06,51.008,73.0,89.0,0.89,AU,1.603054e+09
3,3,rikitea,-23.12,-134.97,74.858,81.0,100.0,8.27,PF,1.603054e+09
4,4,waipawa,-41.41,175.52,57.200,76.0,100.0,10.30,NZ,1.603053e+09

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [35]:
humidity=[]
for x in np.arange(0,len(cities_df['Humidity']),1):
    humidity.append((cities_df['Humidity'][x]))
locations=[]
for x in np.arange(0,len(cities_df['Lat']),1):
    locations.append((cities_df['Lat'][x],cities_df['Lng'][x]))

In [36]:
gmaps.configure(api_key=g_key)

figure_layout = { 'width': '700px', 
                 'height': '500px', 
                 'border': '1px solid black', 
                 'padding': '1px', 'margin': 
                 '0 auto 0 auto' }

In [37]:
fig = gmaps.figure(layout=figure_layout)
fig.add_layer(gmaps.heatmap_layer(locations, weights=humidity))
fig

Figure(layout=FigureLayout(border='1px solid black', height='500px', margin='0 auto 0 auto', padding='1px', wi…

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [38]:
vac_df=cities_df.loc[cities_df['Max Temp']>70]
vac_df=vac_df.loc[vac_df['Max Temp']<80]
vac_df=vac_df.loc[vac_df['Windspeed']<10]
vac_df=vac_df.loc[vac_df['Cloudiness']==0]
vac_df

,Unnamed: 0,Cities,Lat,Lng,Max Temp,Humidity,Cloudiness,Windspeed,Country,Date
79,87,marsa matruh,31.35,27.25,71.600,78.0,0.0,3.78,EG,1.603054e+09
95,103,mount darwin,-16.77,31.58,72.482,27.0,0.0,1.51,ZW,1.603054e+09
101,109,ambilobe,-13.20,49.05,71.456,71.0,0.0,2.00,MG,1.603054e+09
106,114,chuy,-33.70,-53.46,72.482,70.0,0.0,3.41,UY,1.603054e+09
192,210,pirganj,25.85,88.36,75.506,69.0,0.0,1.00,BD,1.603054e+09
220,241,asyut,27.18,31.18,75.200,50.0,0.0,4.10,EG,1.603054e+09
233,256,tura,25.52,90.22,72.644,90.0,0.0,0.73,IN,1.603054e+09
244,268,kariba,-16.52,28.80,76.946,31.0,0.0,1.52,ZW,1.603054e+09
274,300,alexandria,31.22,29.96,75.200,78.0,0.0,2.60,EG,1.603053e+09
287,314,kahna nau,31.37,74.37,71.600,60.0,0.0,1.43,PK,1.603054e+09
291,318,poum,-20.23,164.02,73.634,74.0,0.0,7.55,NC,1.603054e+09
295,324,buraydah,26.33,43.98,73.400,23.0,0.0,2.10,SA,1.603054e+09
322,352,general roca,-39.03,-67.58,77.000,23.0,0.0,2.60,AR,1.603054e+09
343,373,erdemli,36.60,34.31,71.204,71.0,0.0,0.23,TR,1.603054e+09
348,378,rosetta,31.40,30.42,75.200,78.0,0.0,2.60,EG,1.603054e+09
356,386,grand gaube,-20.01,57.66,71.996,74.0,0.0,1.34,MU,1.603054e+09
375,405,salalah,17.02,54.09,78.800,34.0,0.0,2.10,OM,1.603054e+09
378,408,turbat,26.00,63.04,73.958,17.0,0.0,8.70,PK,1.603054e+09
405,439,xai-xai,-25.05,33.64,72.086,70.0,0.0,4.65,MZ,1.603053e+09
411,447,ibra,22.69,58.53,75.002,15.0,0.0,4.57,OM,1.603054e+09
465,511,kutum,14.20,24.67,77.576,18.0,0.0,3.74,SD,1.603054e+09
528,584,malangwa,26.86,85.56,73.004,72.0,0.0,1.11,NP,1.603054e+09
541,597,tahta,26.77,31.50,75.200,41.0,0.0,4.10,EG,1.603053e+09

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [39]:
hotel_df=vac_df
print(len(hotel_df))

23

In [40]:
ticker=0
hotel=[]
locations=[]
for x in np.arange(0,len(hotel_df),1):   
    print(f"Proccessing record {ticker+1}")
    url=f"https://maps.googleapis.com/maps/api/place/nearbysearch/json?parameters"
    params={"location":(f"{hotel_df.iloc[ticker][2]},{hotel_df.iloc[ticker][3]}"),
    "radius":"5000","type": "lodging","key": f"{g_key}"}
    response=requests.get(url,params=params).json()
    
    try:
        print(f"Hotel {response['results'][0]['name']} found!")
        hotel.append(response['results'][0]['name'])
       # locations.append((response['results'][0]['geometry']['location']['lat']),(response['results'][0]['geometry']['location']['lng']))
        ticker+=1
    except:
        print("No hotel found within range!")
        hotel.append(None)
        ticker+=1
        pass
hotel_df['Hotel Name']=hotel

Proccessing record 1
Hotel Beau Site found!
Proccessing record 2
No hotel found within range!
Proccessing record 3
Hotel Hôtel & Restaurant DIANA Ambilobe found!
Proccessing record 4
Hotel Nuevo Hotel Plaza found!
Proccessing record 5
Hotel Haque Mansion found!
Proccessing record 6
Hotel Florence Hotel Assiut found!
Proccessing record 7
Hotel Hotel RIKMAN Continental found!
Proccessing record 8
Hotel Caribbea Bay Hotel found!
Proccessing record 9
Hotel Royal Crown Hotel found!
Proccessing record 10
Hotel Ahle hadees masjid kahna nau found!
Proccessing record 11
Hotel Gîte kajeon found!
Proccessing record 12
Hotel Mövenpick Hotel Qassim found!
Proccessing record 13
Hotel Hotel El Recreo found!
Proccessing record 14
Hotel Denizkumu Hotel found!
Proccessing record 15
Hotel Green Valley found!
Proccessing record 16
Hotel Veranda Paul et Virginie Hotel & Spa found!
Proccessing record 17
Hotel HAMDAN PLAZA HOTEL found!
Proccessing record 18
Hotel Mubashar Quarters found!
Proccessing record 19
Hotel Platinum Hotel found!
Proccessing record 20
Hotel مزرعة راحة النفوس المنزفة found!
Proccessing record 21
Hotel Dibbo areaمنطقة دبو found!
Proccessing record 22
Hotel Prem Meat House found!
Proccessing record 23
Hotel Møhãmęd Tãręk 🏠 found!

In [41]:
hotel_df=hotel_df.dropna()
locations=[]
names=[]
cities=[]
countries=[]
params=[]
locations=hotel_df.iloc[:,2:4]
names=hotel_df['Hotel Name'].tolist()
cities=hotel_df['Cities'].tolist()
countries=hotel_df['Country'].tolist()
for x in np.arange(0,len(names),1):
    params.append(f"Name: {names[x]}, City: {cities[x]}, Country: {countries[x]}")

# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{Cities}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [42]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations,info_box_content=params)
fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(border='1px solid black', height='500px', margin='0 auto 0 auto', padding='1px', wi…